using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Camera_02 : MonoBehaviour
{
    [SerializeField] GameObject player;

    Vector3 currentPos;//現在のカメラ位置
    Vector3 pastPos;//過去のカメラ位置

    Vector3 diff;//移動距離

    private float CameraHeight = 2;

    // Start is called before the first frame update
    void Start()
    {
        //最初のプレイヤーの位置の取得
        pastPos = player.transform.position;
    }

    // Update is called once per frame
    void Update()
    {
        //------カメラの移動------

        //プレイヤーの現在地の取得
        currentPos = player.transform.position;

        diff = currentPos - pastPos;

        transform.position = Vector3.Lerp(transform.position, transform.position + diff, 2.0f);//カメラをプレイヤーの移動差分だけうごかす

        pastPos = currentPos;


        //------カメラの回転------

        // マウスの移動量を取得
        float mx = Input.GetAxis("Mouse X");
        float my = Input.GetAxis("Mouse Y");

        // X方向に一定量移動していれば横回転
        if (Mathf.Abs(mx) > 0.0000001f)
        {
            // 回転軸はワールド座標のY軸
            transform.RotateAround(player.transform.position, Vector3.up, mx);
        }

        // Y方向に一定量移動していれば縦回転
        if (Mathf.Abs(my) > 0.00000001f)
        {
            // 回転軸はカメラ自身のX軸
            transform.RotateAround(player.transform.position, transform.right, -my);

            if ((CameraHeight - my) < 0 || (CameraHeight - my) > 6)
            {
                my = 0;
            }
            CameraHeight -= my / 16;
        }
    }
}
